Name:           ros-jade-ecto-pcl
Version:        0.4.3
Release:        0%{?dist}
Summary:        ROS ecto_pcl package

Group:          Development/Libraries
License:        BSD
URL:            http://plasmodic.github.io/ecto_pcl
Source0:        %{name}-%{version}.tar.gz

Requires:       boost-devel
Requires:       ros-jade-ecto
Requires:       ros-jade-ecto-ros
Requires:       ros-jade-pcl-conversions
Requires:       ros-jade-sensor-msgs
BuildRequires:  boost-devel
BuildRequires:  python-nose
BuildRequires:  ros-jade-catkin
BuildRequires:  ros-jade-ecto
BuildRequires:  ros-jade-ecto-ros
BuildRequires:  ros-jade-pcl-conversions
BuildRequires:  ros-jade-rosunit
BuildRequires:  ros-jade-sensor-msgs

%description
Ecto bindings for common PCL functionality.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/jade" \
        -DCMAKE_PREFIX_PATH="/opt/ros/jade" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/jade

%changelog
* Wed Sep 02 2015 Vincent Rabaud <vincent.rabaud@gmail.com> - 0.4.3-0
- Autogenerated by Bloom

* Mon Apr 20 2015 Vincent Rabaud <vincent.rabaud@gmail.com> - 0.4.2-0
- Autogenerated by Bloom

